name: Create Release

on:
  push:
    branches:
      - release

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release-job

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to release branch
        run: |
          git fetch origin release
          git checkout release

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 20
          check-latest: true

      - name: Install dependencies using Yarn
        run: yarn install

      - name: Create release tag on release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Push release tags to remote
        run: |
          git push --tags

      - name: Checkout dev branch
        run: |
          git fetch origin dev
          git checkout dev

      - name: Merge release branch into dev
        run: |
          git merge release

      - name: Push merge commit to dev
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git push origin dev
